// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYwqqK0prhwIWfKr4XadCsVOimoiyF3n0',
    appId: '1:225987825210:android:363216159c6cbdf0b62f03',
    messagingSenderId: '225987825210',
    projectId: 'all-my-notes-app',
    storageBucket: 'all-my-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsgHHU0W5vWO3Fj7ex9z9fFxhAs_f9Dmg',
    appId: '1:225987825210:ios:527ef58658fae750b62f03',
    messagingSenderId: '225987825210',
    projectId: 'all-my-notes-app',
    storageBucket: 'all-my-notes-app.appspot.com',
    androidClientId: '225987825210-nnr0tsgmdfve6pd1jen4gduf0n5sia27.apps.googleusercontent.com',
    iosClientId: '225987825210-3olb7ij6pobdis6fcp64uuk221krvph1.apps.googleusercontent.com',
    iosBundleId: 'com.app.demoapp',
  );
}
